/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.toedter.calendar.JDateChooser;
import controlador.controladorAsistencias;
import controlador.controladorBeneficiario;
import java.awt.Container;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import modelo.curso;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author pc
 */
public class vistaRegistroAsistencias extends javax.swing.JFrame {
    controladorAsistencias  controlador = new controladorAsistencias(this);

    /**
     * Creates new form Asistencia
     */
    public vistaRegistroAsistencias() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Asistencia de beneficiarios");
        JDateChooser jDateChooser3 = new JDateChooser();
        Calendar cal = Calendar.getInstance(); // Obtenemos una instancia de la fecha actual
        jDateChooser3.setDate(cal.getTime()); // Establecemos la fecha actual como fecha por defecto
        // Agregar el JDateChooser al JFrame
        Container contentPane = this.getContentPane();
        contentPane.add(jDateChooser3);
        controlador.llenarCbxCursoFecha();
        
        
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        // Agregar un WindowListener para controlar el cierre de la ventana
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                // Aquí puedes realizar acciones adicionales antes de cerrar la vista,
                // o mostrar un cuadro de diálogo de confirmación para cerrar.
                // Por ejemplo:
                int opcion = JOptionPane.showConfirmDialog(vistaRegistroAsistencias.this, "¿Deseas cerrar la ventana?", "Confirmar cierre", JOptionPane.YES_NO_OPTION);
                if (opcion == JOptionPane.YES_OPTION) {
                    
                    dispose();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        Jbtn_guardar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Asistencia = new javax.swing.JLabel();
        Jbtn_BuscarAsistencia = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblBeneficiariosCurso = new javax.swing.JTable();
        dtcFechaActual = new com.toedter.calendar.JDateChooser();
        jLabel5 = new javax.swing.JLabel();
        Jbtn_GenerarReporteEnPdf = new javax.swing.JButton();
        cbxCursos = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(228, 244, 251));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(1350, 333));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jbtn_guardar.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Jbtn_guardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IconoGuardar.png"))); // NOI18N
        Jbtn_guardar.setText("GUARDAR");
        Jbtn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_guardarActionPerformed(evt);
            }
        });
        jPanel2.add(Jbtn_guardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(279, 472, -1, 100));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setText("Cursos:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 42, 83, -1));

        Asistencia.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Asistencia.setText("REGISTRO DE ASISTENCIAS");
        jPanel2.add(Asistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 0, -1, -1));

        Jbtn_BuscarAsistencia.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 20)); // NOI18N
        Jbtn_BuscarAsistencia.setText("Buscar");
        Jbtn_BuscarAsistencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_BuscarAsistenciaActionPerformed(evt);
            }
        });
        jPanel2.add(Jbtn_BuscarAsistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, 120, 27));

        tblBeneficiariosCurso.setAutoCreateRowSorter(true);
        tblBeneficiariosCurso.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tblBeneficiariosCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tblBeneficiariosCurso);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 127, 1054, 322));

        dtcFechaActual.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(dtcFechaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 42, 172, 27));

        jLabel5.setBackground(new java.awt.Color(204, 204, 255));
        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("Fecha:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 42, -1, -1));

        Jbtn_GenerarReporteEnPdf.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        Jbtn_GenerarReporteEnPdf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pdf-icon.png"))); // NOI18N
        Jbtn_GenerarReporteEnPdf.setText("GENERAR REPORTES");
        Jbtn_GenerarReporteEnPdf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn_GenerarReporteEnPdfActionPerformed(evt);
            }
        });
        jPanel2.add(Jbtn_GenerarReporteEnPdf, new org.netbeans.lib.awtextra.AbsoluteConstraints(656, 471, -1, 102));

        jPanel2.add(cbxCursos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 220, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoParaAgregar.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1152, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 625, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn_BuscarAsistenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_BuscarAsistenciaActionPerformed
        controlador.consultarBeneficiario(tblBeneficiariosCurso);
    }//GEN-LAST:event_Jbtn_BuscarAsistenciaActionPerformed

    private void Jbtn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_guardarActionPerformed
        
        controlador.insertarAsistencias();
    }//GEN-LAST:event_Jbtn_guardarActionPerformed

    private void Jbtn_GenerarReporteEnPdfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn_GenerarReporteEnPdfActionPerformed
        try {
            generarListaAsistencias();
        } catch (SQLException ex) {
            Logger.getLogger(vistaBeneficiarios.class.getName()).log(Level.SEVERE, null, ex);
        } catch (JRException ex) {
            Logger.getLogger(vistaBeneficiarios.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_Jbtn_GenerarReporteEnPdfActionPerformed

 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaRegistroAsistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaRegistroAsistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaRegistroAsistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaRegistroAsistencias.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaRegistroAsistencias().setVisible(true);
            }
        });
    }
    
    private void generarListaAsistencias() throws SQLException, JRException {
    Connection conexion;
    try {
        String usuario = "postgres";
        String contrasena = "d123456";
        String base = "bdescuela";

        conexion = DriverManager.getConnection("jdbc:postgresql://127.0.0.1/" + base + "?" + "user=" + usuario + "&password=" + contrasena);

        conexion.setAutoCommit(false);

        if (conexion != null) {
            System.out.println("Conexion lista");
        }

        String report = System.getProperty("user.dir") + "/src/main/resources/report1.jrxml";

        JasperReport jasperReport = JasperCompileManager.compileReport(report);

        // No se definen parámetros para el informe

        JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, conexion);

        JasperViewer.viewReport(jasperPrint, false);
    } catch (JRException ex) {
        Logger.getLogger(controladorBeneficiario.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    

   


  
    
    

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Asistencia;
    private javax.swing.JButton Jbtn_BuscarAsistencia;
    private javax.swing.JButton Jbtn_GenerarReporteEnPdf;
    private javax.swing.JButton Jbtn_guardar;
    private javax.swing.JComboBox<curso> cbxCursos;
    public com.toedter.calendar.JDateChooser dtcFechaActual;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable tblBeneficiariosCurso;
    // End of variables declaration//GEN-END:variables

    public JComboBox<curso> getCbxCursos() {
        return cbxCursos;
    }

    public void setCbxCursos(JComboBox<curso> cbxCursos) {
        this.cbxCursos = cbxCursos;
    }

    public JDateChooser getDtcFechaActual() {
        return dtcFechaActual;
    }

    public void setDtcFechaActual(JDateChooser dtcFechaActual) {
        this.dtcFechaActual = dtcFechaActual;
    }

    public JTable getTblBeneficiariosCurso() {
        return tblBeneficiariosCurso;
    }

    public void setTblBeneficiariosCurso(JTable tblBeneficiariosCurso) {
        this.tblBeneficiariosCurso = tblBeneficiariosCurso;
    }
    
    
    
    

    
}
