/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import idao.IObserverVistaMenuPrincipal;
import javax.swing.JFrame;

/**
 *
 * @author Asus
 */
public class vistaMenuPrincipal extends javax.swing.JFrame implements IObserverVistaMenuPrincipal{
    vistaUsuarios vistaUsuarios = new vistaUsuarios();
    vistaBeneficiarios vistaBeneficiarios = new vistaBeneficiarios();
    vistaMenuMantenedores vistaMantenedores = new vistaMenuMantenedores();
    /**
     * Creates new form vistaMenuPrincipal
     */
    public vistaMenuPrincipal() {
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        vistaMantenedores.addObserver(this);
        vistaBeneficiarios.addObserver(this);
    }
    
    @Override
    public void MostrarVentana() {
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnUsuarios = new javax.swing.JButton();
        btnBeneficiarios = new javax.swing.JButton();
        btnMantenedores = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnUsuarios.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        btnUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/DatosUsuarios.png"))); // NOI18N
        btnUsuarios.setText("Datos Usuario");
        btnUsuarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUsuarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 280, 300));

        btnBeneficiarios.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        btnBeneficiarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Beneficiario.png"))); // NOI18N
        btnBeneficiarios.setText("Beneficiarios");
        btnBeneficiarios.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBeneficiarios.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBeneficiarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBeneficiariosActionPerformed(evt);
            }
        });
        jPanel1.add(btnBeneficiarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, 280, 290));

        btnMantenedores.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        btnMantenedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Mantenedor.png"))); // NOI18N
        btnMantenedores.setText("Mantenedores");
        btnMantenedores.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMantenedores.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMantenedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMantenedoresActionPerformed(evt);
            }
        });
        jPanel1.add(btnMantenedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 20, 280, 300));

        jButton4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 22)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Registro.png"))); // NOI18N
        jButton4.setText("Asistencia");
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 280, 290));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FondoMenu.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -30, 1240, 730));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBeneficiariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBeneficiariosActionPerformed
        vistaBeneficiarios.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnBeneficiariosActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
        vistaUsuarios.setVisible(true);
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnMantenedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMantenedoresActionPerformed
        vistaMantenedores.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnMantenedoresActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBeneficiarios;
    private javax.swing.JButton btnMantenedores;
    private javax.swing.JButton btnUsuarios;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
